#!/bin/bash

# 1. install jdk
yum install java-1.8.0 -y

# 2. install tomcat
wget https://mirror.navercorp.com/apache/tomcat/tomcat-8/v8.5.69/bin/apache-tomcat-8.5.69.tar.gz

# 3. create user & group
groupadd -g 9999  sysadmin
useradd -u 9999  -g sysadmin   sysadmin  

# 4. adjust directory & permission
sudo -u sysadmin  tar xvfz  apache-tomcat-8.5.69.tar.gz  -C ~sysadmin/

# 5. install git for sample-code
yum install git -y
cd ~sysadmin/apache-tomcat-8.5.69/webapps
sudo -u sysadmin  mv ROOT ROOT.tmp
sudo -u sysadmin  git clone  https://github.com/neotusca/jsession-test.git  ~sysadmin/apache-tomcat-8.5.69/webapps/ROOT

# 6. execute tomcat
sudo -u sysadmin  ~sysadmin/apache-tomcat-8.5.69/bin/startup.sh
