#!/bin/bash

# 1. install jdk
yum install java-1.8.0 -y

# 2. install tomcat
wget https://mirror.navercorp.com/apache/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
tar xvfz apache-tomcat-9.0.64.tar.gz

# 3. create user & group
groupadd -g 9999  sysadmin
useradd -u 9999  -g sysadmin   sysadmin  

# 4. adjust directory & permission
mv apache-tomcat-9.0.64       /home/sysadmin
chown -R  sysadmin:sysadmin   /home/sysadmin/apache-tomcat-9.0.64

# 5. execute tomcat
sudo -u sysadmin  /home/sysadmin/apache-tomcat-9.0.64/bin/startup.sh
